# Generated by Django 4.2.2 on 2023-06-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0002_aboutproject_delete_about_delete_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutproject',
            name='image',
            field=models.ImageField(default='img/default.jpg', upload_to='static/img/'),
        ),
        migrations.AddField(
            model_name='aboutproject',
            name='technology',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
