# Generated by Django 4.2.2 on 2023-06-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0004_remove_aboutproject_image_aboutproject_image_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutproject',
            name='image_project',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
