# Generated by Django 4.2.2 on 2023-06-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0005_alter_aboutproject_image_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutproject',
            name='technology',
            field=models.CharField(max_length=200),
        ),
    ]
