# Generated by Django 4.2.2 on 2023-06-13 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0006_alter_aboutproject_technology'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutproject',
            old_name='image_project',
            new_name='image',
        ),
    ]
