# Generated by Django 4.2.2 on 2023-06-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0007_rename_image_project_aboutproject_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
