# Generated by Django 4.2.2 on 2023-06-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0008_about_me'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_me',
            options={'verbose_name': 'About_me', 'verbose_name_plural': 'About_me'},
        ),
        migrations.AddField(
            model_name='about_me',
            name='education',
            field=models.CharField(default='none', max_length=300),
        ),
        migrations.AddField(
            model_name='about_me',
            name='name',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='about_me',
            name='skills',
            field=models.TextField(default='none'),
        ),
    ]
