# Generated by Django 4.2.2 on 2023-06-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0009_alter_about_me_options_about_me_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_me',
            name='email',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
