# Generated by Django 4.2.2 on 2023-06-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0010_about_me_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_me',
            name='education',
        ),
    ]
