# Generated by Django 4.2.2 on 2023-06-22 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0012_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
    ]
