# Generated by Django 4.2.2 on 2023-06-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0013_alter_experience_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_me',
            name='telephone',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
