# Generated by Django 4.2.2 on 2023-06-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0014_about_me_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_me',
            old_name='skills',
            new_name='age',
        ),
        migrations.AddField(
            model_name='about_me',
            name='certifications',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='about_me',
            name='intro',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='about_me',
            name='preferences',
            field=models.TextField(default='none', max_length=500),
        ),
    ]
