# Generated by Django 4.2.2 on 2023-06-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0015_rename_skills_about_me_age_about_me_certifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_me',
            name='age',
            field=models.TextField(default='none', max_length=20),
        ),
    ]
