# Generated by Django 4.2.2 on 2023-06-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0017_alter_about_me_certifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
