# Generated by Django 4.2.2 on 2023-06-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0018_delete_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutproject',
            name='preview',
            field=models.TextField(default='none', max_length=150),
        ),
    ]
