# Generated by Django 4.2.2 on 2023-06-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0019_aboutproject_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutproject',
            name='link',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
