# Generated by Django 4.2.2 on 2023-06-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0020_aboutproject_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutproject',
            name='link',
            field=models.CharField(default='none', max_length=70),
        ),
    ]
